name: Build APK & Upload to Firebase App Distribution
on:
  push:
    branches:
      - master
      - app-distribution
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
  upload-apk:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: android/app/build/outputs/apk/release/app-release.apk
